In [6]:
#Author: Datzael Gomez
#Data Dictionary Variables 
'''
Because the data in excel sheet doesn't have well defined variable names it is not easy to know
what data is needed for the analysis, therefore an extra step is needed to 
remove all the unnessary data and translate what each variable signifies using 
a data dictionary that is provided. The end goal is to remove all the unecessary data and change the variable names to 
more definite and understandable names.
'''
import pandas as pd
import numpy as np
#load Data dictionay using pandas
df_dictionary = pd.read_csv('CollegeScorecardDataDictionarydata_dictionary.csv')
#only want to look at variable name and their significance
df_translate= df_dictionary[['NAME OF DATA ELEMENT','VARIABLE NAME']]
#Drop any NaN inputs
df_translate= df_translate.dropna()
#save variable indexes
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('SAT')]
print(x)
y= x.index.get_values()
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('ACT')]
print(x)
y=np.append(y,x.index.get_values())
y= np.delete(y, 9)
y = np.delete(y,9)
print(y)
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('Total share of enrollment of undergraduate degree-seeking students')]
print(x)
y=np.append(y,x.index.get_values())
print(y)
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('First-time, full-time student retention rate at four-year institutions')]
print(x)
y=np.append(y,x.index.get_values())
print(y)
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('Share of')]
print(x)
y=np.append(y,x.index.get_values())
print(x)
print(y)
y=y[:-10]
y=np.delete(y,-10)
y=np.delete(y,-9)
y=np.delete(y,-8)
y=np.delete(y,-7)
y=np.delete(y,-6)
print(y)
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('The median debt for')]
print(x)
y=np.append(y,x.index.get_values())
print(y)
x= df_translate.loc[df_translate['NAME OF DATA ELEMENT'].str.contains('Enrollment')]
print(x)
y=np.append(y,x.index.get_values())
print(y)
y=np.append(y,[3,4,5,6])
y.sort()
df= df_translate.ix[y]
df_names=df['VARIABLE NAME'].tolist()

                                  NAME OF DATA ELEMENT VARIABLE NAME
275  25th percentile of SAT scores at the instituti...       SATVR25
276  75th percentile of SAT scores at the instituti...       SATVR75
277  25th percentile of SAT scores at the instituti...       SATMT25
278  75th percentile of SAT scores at the instituti...       SATMT75
279  25th percentile of SAT scores at the instituti...       SATWR25
280  75th percentile of SAT scores at the instituti...       SATWR75
281  Midpoint of SAT scores at the institution (cri...      SATVRMID
282   Midpoint of SAT scores at the institution (math)      SATMTMID
283  Midpoint of SAT scores at the institution (wri...      SATWRMID
296  Average SAT equivalent score of students admitted       SAT_AVG
297  Average SAT equivalent score of students admit...   SAT_AVG_ALL
                            NAME OF DATA ELEMENT VARIABLE NAME
284  25th percentile of the ACT cumulative score       ACTCM25
285  75th percentile of the ACT cumulative score       ACTCM75
286     25th percentile of the ACT English score       ACTEN25
287     75th percentile of the ACT English score       ACTEN75
288        25th percentile of the ACT math score       ACTMT25
289        75th percentile of the ACT math score       ACTMT75
290     25th percentile of the ACT writing score       ACTWR25
291     75th percentile of the ACT writing score       ACTWR75
292         Midpoint of the ACT cumulative score      ACTCMMID
293            Midpoint of the ACT English score      ACTENMID
294               Midpoint of the ACT math score      ACTMTMID
295            Midpoint of the ACT writing score      ACTWRMID
[275 276 277 278 279 280 281 282 283 284 285 286 287 288 289 290 291 292
 293 294 295]
                                   NAME OF DATA ELEMENT VARIABLE NAME
530   Total share of enrollment of undergraduate deg...    UGDS_WHITE
531   Total share of enrollment of undergraduate deg...    UGDS_BLACK
532   Total share of enrollment of undergraduate deg...     UGDS_HISP
533   Total share of enrollment of undergraduate deg...    UGDS_ASIAN
534   Total share of enrollment of undergraduate deg...     UGDS_AIAN
535   Total share of enrollment of undergraduate deg...     UGDS_NHPI
536   Total share of enrollment of undergraduate deg...     UGDS_2MOR
537   Total share of enrollment of undergraduate deg...      UGDS_NRA
538   Total share of enrollment of undergraduate deg...     UGDS_UNKN
539   Total share of enrollment of undergraduate deg...  UGDS_WHITENH
540   Total share of enrollment of undergraduate deg...  UGDS_BLACKNH
541   Total share of enrollment of undergraduate deg...      UGDS_API
542   Total share of enrollment of undergraduate deg...  UGDS_AIANOLD
543   Total share of enrollment of undergraduate deg...  UGDS_HISPOLD
1971  Total share of enrollment of undergraduate deg...      UGDS_MEN
1972  Total share of enrollment of undergraduate deg...    UGDS_WOMEN
[ 275  276  277  278  279  280  281  282  283  284  285  286  287  288  289
  290  291  292  293  294  295  530  531  532  533  534  535  536  537  538
  539  540  541  542  543 1971 1972]
                                   NAME OF DATA ELEMENT        VARIABLE NAME
663   First-time, full-time student retention rate a...              RET_FT4
2039  First-time, full-time student retention rate a...       RET_FT4_POOLED
2049  First-time, full-time student retention rate a...  RET_FT4_POOLED_SUPP
[ 275  276  277  278  279  280  281  282  283  284  285  286  287  288  289
  290  291  292  293  294  295  530  531  532  533  534  535  536  537  538
  539  540  541  542  543 1971 1972  663 2039 2049]
                                   NAME OF DATA ELEMENT VARIABLE NAME
551   Share of undergraduate, degree-/certificate-se...      PPTUG_EF
552   Share of undergraduate, degree-/certificate-se...     PPTUG_EF2
630   Share of entering undergraduate students who a...   PFTFTUG1_EF
1834  Share of students who received a federal loan ...     LOAN_EVER
1835  Share of students who received a Pell Grant wh...     PELL_EVER
1839                           Share of female students        FEMALE
1840                          Share of married students       MARRIED
1841                        Share of dependent students     DEPENDENT
1842                          Share of veteran students       VETERAN
1843                 Share of first-generation students     FIRST_GEN
1861  Share of students who submitted FAFSAs to only...       FSEND_1
1862  Share of students who submitted FAFSAs to two ...       FSEND_2
1863  Share of students who submitted FAFSAs to thre...       FSEND_3
1864  Share of students who submitted FAFSAs to four...       FSEND_4
1865  Share of students who submitted FAFSAs to at l...       FSEND_5
1883  Share of students earning over $25,000/year (t...    GT_25K_P10
1909  Share of students earning over $25,000/year (t...     GT_25K_P6
1922  Share of students earning over $25,000/year (t...     GT_25K_P7
1932  Share of students earning over $25,000/year (t...     GT_25K_P8
1937  Share of students earning over $25,000/year (t...     GT_25K_P9
                                   NAME OF DATA ELEMENT VARIABLE NAME
551   Share of undergraduate, degree-/certificate-se...      PPTUG_EF
552   Share of undergraduate, degree-/certificate-se...     PPTUG_EF2
630   Share of entering undergraduate students who a...   PFTFTUG1_EF
1834  Share of students who received a federal loan ...     LOAN_EVER
1835  Share of students who received a Pell Grant wh...     PELL_EVER
1839                           Share of female students        FEMALE
1840                          Share of married students       MARRIED
1841                        Share of dependent students     DEPENDENT
1842                          Share of veteran students       VETERAN
1843                 Share of first-generation students     FIRST_GEN
1861  Share of students who submitted FAFSAs to only...       FSEND_1
1862  Share of students who submitted FAFSAs to two ...       FSEND_2
1863  Share of students who submitted FAFSAs to thre...       FSEND_3
1864  Share of students who submitted FAFSAs to four...       FSEND_4
1865  Share of students who submitted FAFSAs to at l...       FSEND_5
1883  Share of students earning over $25,000/year (t...    GT_25K_P10
1909  Share of students earning over $25,000/year (t...     GT_25K_P6
1922  Share of students earning over $25,000/year (t...     GT_25K_P7
1932  Share of students earning over $25,000/year (t...     GT_25K_P8
1937  Share of students earning over $25,000/year (t...     GT_25K_P9
[ 275  276  277  278  279  280  281  282  283  284  285  286  287  288  289
  290  291  292  293  294  295  530  531  532  533  534  535  536  537  538
  539  540  541  542  543 1971 1972  663 2039 2049  551  552  630 1834 1835
 1839 1840 1841 1842 1843 1861 1862 1863 1864 1865 1883 1909 1922 1932 1937]
[ 275  276  277  278  279  280  281  282  283  284  285  286  287  288  289
  290  291  292  293  294  295  530  531  532  533  534  535  536  537  538
  539  540  541  542  543 1971 1972  663 2039 2049 1839 1840 1841 1842 1843]
                                   NAME OF DATA ELEMENT         VARIABLE NAME
1734    The median debt for students who have completed         GRAD_DEBT_MDN
1735  The median debt for students who have not comp...        WDRAW_DEBT_MDN
1736  The median debt for students with family incom...       LO_INC_DEBT_MDN
1737  The median debt for students with family incom...       MD_INC_DEBT_MDN
1738  The median debt for students with family incom...       HI_INC_DEBT_MDN
1739             The median debt for dependent students          DEP_DEBT_MDN
1740           The median debt for independent students          IND_DEBT_MDN
1741                  The median debt for Pell students         PELL_DEBT_MDN
1742               The median debt for no-Pell students       NOPELL_DEBT_MDN
1743                The median debt for female students       FEMALE_DEBT_MDN
1744                  The median debt for male students         MALE_DEBT_MDN
1745      The median debt for first-generation students     FIRSTGEN_DEBT_MDN
1746  The median debt for not-first-generation students  NOTFIRSTGEN_DEBT_MDN
[ 275  276  277  278  279  280  281  282  283  284  285  286  287  288  289
  290  291  292  293  294  295  530  531  532  533  534  535  536  537  538
  539  540  541  542  543 1971 1972  663 2039 2049 1839 1840 1841 1842 1843
 1734 1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746]
                                  NAME OF DATA ELEMENT VARIABLE NAME
528  Enrollment of undergraduate certificate/degree...          UGDS
529           Enrollment of all undergraduate students            UG
[ 275  276  277  278  279  280  281  282  283  284  285  286  287  288  289
  290  291  292  293  294  295  530  531  532  533  534  535  536  537  538
  539  540  541  542  543 1971 1972  663 2039 2049 1839 1840 1841 1842 1843
 1734 1735 1736 1737 1738 1739 1740 1741 1742 1743 1744 1745 1746  528  529]

C:\Users\ericm\Anaconda2\lib\site-packages\ipykernel_launcher.py:58: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated

In [7]:
df2016 = pd.read_csv('MERGED2015_16_PP.csv')
df2016= df2016[df_names]
print(df2016)

                                                 INSTNM              CITY  \
0                              Alabama A & M University            Normal
1                   University of Alabama at Birmingham        Birmingham
2                                    Amridge University        Montgomery
3                   University of Alabama in Huntsville        Huntsville
4                              Alabama State University        Montgomery
5                             The University of Alabama        Tuscaloosa
6                     Central Alabama Community College    Alexander City
7                               Athens State University            Athens
8                       Auburn University at Montgomery        Montgomery
9                                     Auburn University            Auburn
10                          Birmingham Southern College        Birmingham
11               Chattahoochee Valley Community College       Phenix City
12                            Concordia College Alabama             Selma
13                          South University-Montgomery        Montgomery
14                   Enterprise State Community College        Enterprise
15             James H Faulkner State Community College       Bay Minette
16                                  Faulkner University        Montgomery
17                      Gadsden State Community College           Gadsden
18                 New Beginning College of Cosmetology       Albertville
19      George C Wallace State Community College-Dothan            Dothan
20    George C Wallace State Community College-Hance...        Hanceville
21       George C Wallace State Community College-Selma             Selma
22                        Herzing University-Birmingham        Birmingham
23                                   Huntingdon College        Montgomery
24                        Heritage Christian University          Florence
25      J F Drake State Community and Technical College        Huntsville
26                        Jacksonville State University      Jacksonville
27                    Jefferson Davis Community College           Brewton
28                    Jefferson State Community College        Birmingham
29               John C Calhoun State Community College            Tanner
...                                                 ...               ...
7563                   Strayer University-Morrow Campus            Morrow
7564                  Strayer University-Roswell Campus           Roswell
7565             Strayer University-Douglasville Campus      Douglasville
7566                 Strayer University-Lithonia Campus          Lithonia
7567                 Strayer University-Savannah Campus          Savannah
7568                  Strayer University-Augusta Campus           Augusta
7569                        Strayer University-Columbus          Columbus
7570                 Strayer University-Columbia Campus          Columbia
7571               Strayer University-Charleston Campus  North Charleston
7572                          Strayer University-Irving            Irving
7573                            Strayer University-Katy           Houston
7574               Strayer University-Northwest Houston           Houston
7575                           Strayer University-Plano             Plano
7576                      Strayer University-Cedar Hill        Cedar Hill
7577                    Strayer University-North Dallas            Dallas
7578                     Strayer University-San Antonio       San Antonio
7579                        Strayer University-Stafford          Stafford
7580                                     Unitek College           Fremont
7581        Relay Graduate School of Education - Newark            Newark
7582   Relay Graduate School of Education - New Orleans       New Orleans
7583                           WestMed College - Merced            Merced
7584                                    Vantage College           El Paso
7585                                    Vantage College            Austin
7586          SAE Institute of Technology San Francisco        Emeryville
7587                  Rasmussen College - Overland Park     Overland Park
7588  National Personal Training Institute of Cleveland  Highland Heights
7589  Bay Area Medical Academy - San Jose Satellite ...          San Jose
7590                        High Desert Medical College         Lancaster
7591                        Vantage College-San Antonio       San Antonio
7592  American Institute of Pharmaceutical Technolog...            Newark

     STABBR         ZIP  SATVR25  SATVR75  SATMT25  SATMT75  SATWR25  SATWR75  \
0        AL       35762    383.0    470.0    360.0    480.0    370.0    457.0
1        AL  35294-0110    520.0    630.0    520.0    668.0      NaN      NaN
2        AL  36117-3553      NaN      NaN      NaN      NaN      NaN      NaN
3        AL       35899    520.0    650.0    550.0    680.0      NaN      NaN
4        AL  36104-0271    370.0    450.0    360.0    460.0      NaN      NaN
5        AL  35487-0166    490.0    600.0    490.0    610.0    480.0    600.0
6        AL       35010      NaN      NaN      NaN      NaN      NaN      NaN
7        AL       35611      NaN      NaN      NaN      NaN      NaN      NaN
8        AL  36117-3596    450.0    520.0    470.0    540.0      NaN      NaN
9        AL       36849    530.0    630.0    540.0    650.0    520.0    620.0
10       AL       35254    480.0    590.0    500.0    610.0      NaN      NaN
11       AL       36869      NaN      NaN      NaN      NaN      NaN      NaN
12       AL       36701      NaN      NaN      NaN      NaN      NaN      NaN
13       AL       36116      NaN      NaN      NaN      NaN      NaN      NaN
14       AL  36330-1300      NaN      NaN      NaN      NaN      NaN      NaN
15       AL  36507-2698      NaN      NaN      NaN      NaN      NaN      NaN
16       AL  36109-3390    430.0    520.0    440.0    510.0    430.0    510.0
17       AL       35903      NaN      NaN      NaN      NaN      NaN      NaN
18       AL       35951      NaN      NaN      NaN      NaN      NaN      NaN
19       AL  36303-9234      NaN      NaN      NaN      NaN      NaN      NaN
20       AL  35077-2000      NaN      NaN      NaN      NaN      NaN      NaN
21       AL  36703-2808      NaN      NaN      NaN      NaN      NaN      NaN
22       AL       35209      NaN      NaN      NaN      NaN      NaN      NaN
23       AL  36106-2148    440.0    550.0    450.0    568.0      NaN      NaN
24       AL  35630-9977    380.0    660.0    400.0    610.0    300.0    560.0
25       AL       35811      NaN      NaN      NaN      NaN      NaN      NaN
26       AL       36265    450.0    550.0    440.0    550.0      NaN      NaN
27       AL       36426      NaN      NaN      NaN      NaN      NaN      NaN
28       AL  35215-3098      NaN      NaN      NaN      NaN      NaN      NaN
29       AL       35671      NaN      NaN      NaN      NaN      NaN      NaN
...     ...         ...      ...      ...      ...      ...      ...      ...
7563     GA       30260      NaN      NaN      NaN      NaN      NaN      NaN
7564     GA       30076      NaN      NaN      NaN      NaN      NaN      NaN
7565     GA       30135      NaN      NaN      NaN      NaN      NaN      NaN
7566     GA       30038      NaN      NaN      NaN      NaN      NaN      NaN
7567     GA       31419      NaN      NaN      NaN      NaN      NaN      NaN
7568     GA       30909      NaN      NaN      NaN      NaN      NaN      NaN
7569     GA       31909      NaN      NaN      NaN      NaN      NaN      NaN
7570     SC       29210      NaN      NaN      NaN      NaN      NaN      NaN
7571     SC       29418      NaN      NaN      NaN      NaN      NaN      NaN
7572     TX       75063      NaN      NaN      NaN      NaN      NaN      NaN
7573     TX       77079      NaN      NaN      NaN      NaN      NaN      NaN
7574     TX       77064      NaN      NaN      NaN      NaN      NaN      NaN
7575     TX       75093      NaN      NaN      NaN      NaN      NaN      NaN
7576     TX       75104      NaN      NaN      NaN      NaN      NaN      NaN
7577     TX       75251      NaN      NaN      NaN      NaN      NaN      NaN
7578     TX       78216      NaN      NaN      NaN      NaN      NaN      NaN
7579     TX       77477      NaN      NaN      NaN      NaN      NaN      NaN
7580     CA   945383185      NaN      NaN      NaN      NaN      NaN      NaN
7581     NJ    71023106      NaN      NaN      NaN      NaN      NaN      NaN
7582     LA   701123701      NaN      NaN      NaN      NaN      NaN      NaN
7583     CA   953400000      NaN      NaN      NaN      NaN      NaN      NaN
7584     TX   799064951      NaN      NaN      NaN      NaN      NaN      NaN
7585     TX   787523733      NaN      NaN      NaN      NaN      NaN      NaN
7586     CA       94608      NaN      NaN      NaN      NaN      NaN      NaN
7587     KS   662102786      NaN      NaN      NaN      NaN      NaN      NaN
7588     OH       44143      NaN      NaN      NaN      NaN      NaN      NaN
7589     CA   951131820      NaN      NaN      NaN      NaN      NaN      NaN
7590     CA   935340000      NaN      NaN      NaN      NaN      NaN      NaN
7591     TX   782211361      NaN      NaN      NaN      NaN      NaN      NaN
7592     NJ        7102      NaN      NaN      NaN      NaN      NaN      NaN

             ...           NOTFIRSTGEN_DEBT_MDN             FEMALE  \
0            ...                          14953       0.5472427116
1            ...                          14500       0.6369683532
2            ...                          12500       0.6043956044
3            ...                          15000       0.4779208832
4            ...                          15000        0.612294094
5            ...                          17000        0.607564495
6            ...                           5682       0.5935314685
7            ...                          12500       0.6867392697
8            ...                           9500       0.6838975297
9            ...                          17000       0.5205963123
10           ...                          19701       0.5133333333
11           ...                           5500       0.6103619588
12           ...                           7500       0.2809430255
13           ...                           9500       0.7661442995
14           ...                           5500       0.5046335299
15           ...                           5500       0.6597472924
16           ...                        13462.5       0.6082751209
17           ...              PrivacySuppressed       0.6155440415
18           ...                           5650  PrivacySuppressed
19           ...              PrivacySuppressed       0.6640063847
20           ...                           7377       0.6225886745
21           ...              PrivacySuppressed       0.6196957566
22           ...                          11445       0.8160972785
23           ...                          15000       0.5069124424
24           ...              PrivacySuppressed  PrivacySuppressed
25           ...              PrivacySuppressed        0.551558753
26           ...                          16000       0.5753282654
27           ...              PrivacySuppressed       0.6195488722
28           ...                         4096.5       0.6610738255
29           ...                           5500       0.6019059996
...          ...                            ...                ...
7563         ...                           9501       0.7323172433
7564         ...                           9501       0.7323172433
7565         ...                           9501       0.7323172433
7566         ...                           9501       0.7323172433
7567         ...                           9501       0.7323172433
7568         ...                           9501       0.7323172433
7569         ...                           9501       0.7323172433
7570         ...                           9501       0.7323172433
7571         ...                           9501       0.7323172433
7572         ...                           9501       0.7323172433
7573         ...                           9501       0.7323172433
7574         ...                           9501       0.7323172433
7575         ...                           9501       0.7323172433
7576         ...                           9501       0.7323172433
7577         ...                           9501       0.7323172433
7578         ...                           9501       0.7323172433
7579         ...                           9501       0.7323172433
7580         ...                           9500       0.7954033348
7581         ...              PrivacySuppressed  PrivacySuppressed
7582         ...              PrivacySuppressed  PrivacySuppressed
7583         ...                           9500       0.7472527473
7584         ...                           9500       0.6786941581
7585         ...                           9500       0.6786941581
7586         ...                           5500       0.1211340206
7587         ...                          10821       0.7978077481
7588         ...                           6333       0.3473684211
7589         ...                           5500       0.8681318681
7590         ...                           7521       0.9239280775
7591         ...                         5350.5               0.75
7592         ...              PrivacySuppressed       0.7413793103

                MARRIED          DEPENDENT            VETERAN  \
0          0.0108886547       0.8868984896       0.0042149631
1          0.1076395888       0.6702277767       0.0028220117
2          0.2564102564       0.1172161172  PrivacySuppressed
3          0.1131554738       0.7056117755       0.0059797608
4          0.0088388911        0.864202491  PrivacySuppressed
5           0.053672934       0.8614997814       0.0030607783
6          0.0856643357        0.659965035  PrivacySuppressed
7          0.3670723895       0.2844330557  PrivacySuppressed
8          0.0750228728       0.7429094236        0.005946935
9          0.0219693998       0.9125147117       0.0031384857
10    PrivacySuppressed       0.9777777778  PrivacySuppressed
11         0.2079488999       0.4975159688       0.0078069553
12    PrivacySuppressed        0.815324165  PrivacySuppressed
13         0.2409549853       0.2152923854       0.0180900294
14         0.1533277169       0.5796124684       0.0084245998
15         0.1064981949       0.6432009627       0.0048134777
16         0.1552928533       0.4078452445  PrivacySuppressed
17         0.1354058722       0.5333333333       0.0082901554
18         0.2296296296       0.5111111111  PrivacySuppressed
19         0.1472466081        0.538707103       0.0055865922
20         0.1617921593       0.6172993155       0.0034225264
21         0.0456365092       0.6589271417       0.0080064051
22         0.2348581355       0.1358425014        0.010075275
23         0.0860215054       0.7265745008  PrivacySuppressed
24         0.4545454545  PrivacySuppressed  PrivacySuppressed
25         0.1462829736       0.3525179856  PrivacySuppressed
26          0.106772633       0.7394609537  PrivacySuppressed
27         0.1323308271       0.5969924812  PrivacySuppressed
28         0.1308724832       0.5817353787       0.0047938639
29         0.1492311024       0.5967078189       0.0049815898
...                 ...                ...                ...
7563       0.2229701451       0.0826241629        0.022391183
7564       0.2229701451       0.0826241629        0.022391183
7565       0.2229701451       0.0826241629        0.022391183
7566       0.2229701451       0.0826241629        0.022391183
7567       0.2229701451       0.0826241629        0.022391183
7568       0.2229701451       0.0826241629        0.022391183
7569       0.2229701451       0.0826241629        0.022391183
7570       0.2229701451       0.0826241629        0.022391183
7571       0.2229701451       0.0826241629        0.022391183
7572       0.2229701451       0.0826241629        0.022391183
7573       0.2229701451       0.0826241629        0.022391183
7574       0.2229701451       0.0826241629        0.022391183
7575       0.2229701451       0.0826241629        0.022391183
7576       0.2229701451       0.0826241629        0.022391183
7577       0.2229701451       0.0826241629        0.022391183
7578       0.2229701451       0.0826241629        0.022391183
7579       0.2229701451       0.0826241629        0.022391183
7580       0.2374943668       0.3199639477       0.0085624155
7581  PrivacySuppressed  PrivacySuppressed  PrivacySuppressed
7582  PrivacySuppressed  PrivacySuppressed  PrivacySuppressed
7583       0.1813186813       0.2582417582  PrivacySuppressed
7584       0.2869415808       0.1958762887  PrivacySuppressed
7585       0.2869415808       0.1958762887  PrivacySuppressed
7586       0.0644329897       0.4639175258       0.0283505155
7587       0.2842405029       0.1827951212       0.0124657461
7588       0.1263157895       0.3368421053  PrivacySuppressed
7589       0.1153846154       0.3351648352  PrivacySuppressed
7590       0.1673582296       0.3457814661  PrivacySuppressed
7591       0.3095238095        0.130952381  PrivacySuppressed
7592  PrivacySuppressed       0.0862068966  PrivacySuppressed

              FIRST_GEN  UGDS_MEN  UGDS_WOMEN  RET_FT4_POOLED  \
0          0.3887357227    0.4617      0.5383        0.616384
1          0.3564593301    0.4116      0.5884        0.807657
2          0.5285714286    0.4286      0.5714        0.500000
3          0.3137931034    0.5740      0.4260        0.786986
4           0.369258754    0.3850      0.6150        0.584708
5          0.2329344729    0.4525      0.5475        0.865822
6           0.563976378    0.4017      0.5983             NaN
7          0.4655290102    0.3485      0.6515             NaN
8          0.3906485671    0.3595      0.6405        0.649239
9          0.1860230257    0.5095      0.4905        0.901226
10         0.1772727273    0.5022      0.4978        0.848881
11         0.4247135843    0.3870      0.6130             NaN
12         0.4805491991    0.5541      0.4459        0.505147
13         0.4823701629    0.2500      0.7500        0.463415
14         0.4714975845    0.5177      0.4823             NaN
15         0.4509018036    0.3840      0.6160             NaN
16         0.4462759463    0.3874      0.6126        0.582341
17         0.5311102074    0.3909      0.6091             NaN
18         0.5454545455    0.0000      1.0000             NaN
19          0.526119403    0.3412      0.6588             NaN
20         0.5186820652    0.3700      0.6300             NaN
21         0.5041171089    0.3427      0.6573             NaN
22         0.5342832957    0.4889      0.5111        0.400000
23         0.3338842975    0.4991      0.5009        0.684436
24    PrivacySuppressed    0.9483      0.0517        0.466653
25         0.5821529745    0.4524      0.5476             NaN
26         0.3945124212    0.4312      0.5688        0.730833
27         0.5367521368    0.4392      0.5608             NaN
28         0.4549356223    0.3842      0.6158             NaN
29         0.4740740741    0.4483      0.5517             NaN
...                 ...       ...         ...             ...
7563       0.5288486417       NaN         NaN             NaN
7564       0.5288486417       NaN         NaN             NaN
7565       0.5288486417       NaN         NaN             NaN
7566       0.5288486417       NaN         NaN             NaN
7567       0.5288486417       NaN         NaN             NaN
7568       0.5288486417       NaN         NaN             NaN
7569       0.5288486417       NaN         NaN             NaN
7570       0.5288486417       NaN         NaN             NaN
7571       0.5288486417       NaN         NaN             NaN

In [8]:
#Need to break everything down into categories 
#Start with ethnicity starts with UDGS
y=[]
df_temp= df.loc[df['VARIABLE NAME'].str.contains('UG')]
y=np.append(y,df_temp.index.get_values())
df_temp= df.loc[df['VARIABLE NAME'].str.contains('CITY')]
y=np.append(y,df_temp.index.get_values())
y.sort()
df_temp= df.ix[y]
ethnic = df_temp['VARIABLE NAME'].tolist()
df_ethnic = df2016[ethnic]
len(y)
m=[]
for i in range(len(y)):
    q = df_ethnic.loc[1].isnull()
    if q[i] == False:
        m=np.append(m,ethnic[i])
df_ethnic= df_ethnic[m]  
df_ethnic.dropna()

C:\Users\ericm\Anaconda2\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':

,CITY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,UGDS_MEN,UGDS_WOMEN
0,Normal,4505.0,0.0340,0.9216,0.0058,0.0018,0.0022,0.0018,0.0000,0.0062,0.0266,0.4617,0.5383
1,Birmingham,11269.0,0.5863,0.2541,0.0317,0.0595,0.0023,0.0006,0.0389,0.0181,0.0085,0.4116,0.5884
2,Montgomery,308.0,0.2110,0.3409,0.0195,0.0000,0.0000,0.0032,0.0000,0.0000,0.4253,0.4286,0.5714
3,Huntsville,5829.0,0.7024,0.1230,0.0417,0.0381,0.0130,0.0000,0.0201,0.0317,0.0300,0.5740,0.4260
4,Montgomery,4740.0,0.0165,0.9251,0.0116,0.0032,0.0008,0.0006,0.0114,0.0209,0.0099,0.3850,0.6150
5,Tuscaloosa,31005.0,0.7807,0.1092,0.0399,0.0113,0.0035,0.0009,0.0271,0.0245,0.0029,0.4525,0.5475
6,Alexander City,1546.0,0.7141,0.2600,0.0123,0.0045,0.0019,0.0000,0.0032,0.0019,0.0019,0.4017,0.5983
7,Athens,2904.0,0.7817,0.1185,0.0189,0.0062,0.0152,0.0007,0.0189,0.0055,0.0344,0.3485,0.6515
8,Montgomery,4142.0,0.5355,0.3510,0.0070,0.0241,0.0051,0.0017,0.0316,0.0316,0.0123,0.3595,0.6405
9,Auburn,21551.0,0.8420,0.0671,0.0323,0.0250,0.0063,0.0001,0.0057,0.0131,0.0085,0.5095,0.4905
10,Birmingham,1346.0,0.7912,0.1137,0.0208,0.0535,0.0097,0.0000,0.0089,0.0000,0.0022,0.5022,0.4978
11,Phenix City,1566.0,0.4662,0.4393,0.0453,0.0109,0.0038,0.0057,0.0166,0.0000,0.0121,0.3870,0.6130
12,Selma,379.0,0.0317,0.9077,0.0317,0.0026,0.0000,0.0000,0.0000,0.0264,0.0000,0.5541,0.4459
13,Montgomery,460.0,0.3283,0.5913,0.0217,0.0152,0.0109,0.0087,0.0000,0.0022,0.0217,0.2500,0.7500
14,Enterprise,1528.0,0.6296,0.2435,0.0582,0.0216,0.0046,0.0033,0.0334,0.0007,0.0052,0.5177,0.4823
15,Bay Minette,4372.0,0.6921,0.2246,0.0341,0.0089,0.0185,0.0018,0.0165,0.0016,0.0018,0.3840,0.6160
16,Montgomery,2282.0,0.3996,0.5079,0.0241,0.0026,0.0061,0.0026,0.0193,0.0215,0.0162,0.3874,0.6126
17,Gadsden,4613.0,0.6978,0.1968,0.0308,0.0046,0.0113,0.0011,0.0269,0.0212,0.0095,0.3909,0.6091
18,Albertville,91.0,0.8791,0.0220,0.0989,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
19,Dothan,4173.0,0.6348,0.3094,0.0268,0.0065,0.0055,0.0017,0.0134,0.0000,0.0019,0.3412,0.6588
20,Hanceville,4821.0,0.8486,0.0631,0.0380,0.0073,0.0097,0.0000,0.0000,0.0075,0.0259,0.3700,0.6300
21,Selma,1383.0,0.1902,0.7628,0.0072,0.0029,0.0022,0.0000,0.0043,0.0051,0.0253,0.3427,0.6573
22,Birmingham,360.0,0.3722,0.5083,0.0333,0.0000,0.0028,0.0056,0.0444,0.0000,0.0333,0.4889,0.5111
23,Montgomery,1160.0,0.6310,0.2164,0.0345,0.0060,0.0095,0.0009,0.0310,0.0017,0.0690,0.4991,0.5009
24,Florence,58.0,0.7586,0.1552,0.0172,0.0000,0.0345,0.0000,0.0172,0.0172,0.0000,0.9483,0.0517
25,Huntsville,820.0,0.3671,0.5561,0.0195,0.0073,0.0134,0.0000,0.0207,0.0098,0.0061,0.4524,0.5476
26,Jacksonville,6625.0,0.6981,0.2214,0.0124,0.0059,0.0075,0.0006,0.0000,0.0260,0.0281,0.4312,0.5688
27,Brewton,1036.0,0.5647,0.3098,0.0068,0.0203,0.0193,0.0000,0.0145,0.0000,0.0647,0.4392,0.5608
28,Birmingham,7381.0,0.6708,0.2187,0.0377,0.0191,0.0031,0.0011,0.0285,0.0207,0.0004,0.3842,0.6158
29,Tanner,8547.0,0.6595,0.1864,0.0461,0.0296,0.0161,0.0004,0.0424,0.0075,0.0121,0.4483,0.5517
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7116,Cuyahoga Falls,449.0,0.6102,0.3252,0.0178,0.0267,0.0000,0.0000,0.0134,0.0000,0.0067,0.2650,0.7350
7117,Jacksonville,267.0,0.6442,0.1873,0.1049,0.0300,0.0037,0.0075,0.0225,0.0000,0.0000,0.9551,0.0449
7118,Waco,8160.0,0.3858,0.0706,0.5004,0.0070,0.0043,0.0017,0.0016,0.0001,0.0286,0.6594,0.3406
7119,Vancouver,109.0,0.7798,0.0092,0.0367,0.0275,0.0092,0.0000,0.0826,0.0000,0.0550,0.0000,1.0000
7120,Stow,58.0,0.3621,0.1207,0.0000,0.0000,0.0172,0.0000,0.0172,0.0000,0.4828,0.1034,0.8966
7121,Willoughby Hills,41.0,0.0976,0.7561,0.0000,0.0000,0.0000,0.0000,0.0244,0.0000,0.1220,0.1707,0.8293
7122,Las Vegas,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
7123,Pembroke Pines,361.0,0.0471,0.4238,0.1579,0.0055,0.0000,0.0000,0.0055,0.0000,0.3601,0.3878,0.6122
7124,West Palm Beach,327.0,0.1101,0.5076,0.1407,0.0031,0.0000,0.0000,0.0000,0.0000,0.2385,0.4343,0.5657
7125,Hialeah,406.0,0.0074,0.2020,0.5567,0.0000,0.0025,0.0000,0.0000,0.0000,0.2315,0.4310,0.5690
7126,Lauderdale Lakes,691.0,0.0217,0.7308,0.0535,0.0043,0.0014,0.0014,0.0072,0.0000,0.1795,0.2822,0.7178
7127,Tampa,286.0,0.1608,0.2343,0.0664,0.0000,0.0000,0.0000,0.0245,0.0000,0.5140,0.5524,0.4476
7128,Jacksonville,346.0,0.2514,0.4046,0.0694,0.0145,0.0000,0.0087,0.1272,0.0000,0.1243,0.2861,0.7139
7129,Boynton Beach,283.0,0.1272,0.5018,0.1484,0.0106,0.0000,0.0000,0.0106,0.0000,0.2014,0.2721,0.7279
7130,Margate,273.0,0.0806,0.5311,0.1245,0.0037,0.0000,0.0000,0.0000,0.0000,0.2601,0.4176,0.5824
7131,Miami,174.0,0.0345,0.1322,0.6552,0.0057,0.0000,0.0000,0.1379,0.0000,0.0345,0.2816,0.7184
7132,Orlando,469.0,0.1130,0.2878,0.3731,0.0064,0.0043,0.0021,0.0192,0.0021,0.1919,0.5011,0.4989
7133,Phoenix,147.0,0.0952,0.0204,0.0884,0.0068,0.0000,0.0000,0.0000,0.0000,0.7891,0.5986,0.4014
7134,Houston,374.0,0.0615,0.4439,0.1257,0.0000,0.0027,0.0000,0.0027,0.0000,0.3636,0.4519,0.5481
7135,Madison,53.0,0.8679,0.0377,0.0000,0.0566,0.0189,0.0000,0.0189,0.0000,0.0000,0.0000,1.0000
7136,Bangor,2588.0,0.8794,0.0386,0.0162,0.0070,0.0050,0.0031,0.0124,0.0309,0.0073,0.4687,0.5313
7137,Elgin,64.0,0.6406,0.0469,0.2813,0.0000,0.0000,0.0000,0.0156,0.0156,0.0000,0.0781,0.9219
7138,Southaven,274.0,0.2044,0.7336,0.0182,0.0000,0.0000,0.0000,0.0219,0.0036,0.0182,0.0255,0.9745
7139,Long Beach,285.0,0.0842,0.0316,0.6737,0.0491,0.0000,0.0140,0.0877,0.0000,0.0596,0.9754,0.0246
7140,Kirkland,579.0,0.5838,0.0777,0.1019,0.0501,0.0173,0.0190,0.0466,0.0000,0.1036,0.5682,0.4318
7141,Monroe,9.0,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.8889,0.1111
7142,Delray Beach,13.0,0.3077,0.2308,0.4615,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.5385,0.4615
7144,Lafayette,59.0,0.6441,0.1356,0.0339,0.0508,0.0000,0.0169,0.0000,0.0000,0.1186,0.8475,0.1525
7145,Los Angeles,226.0,0.0442,0.0310,0.0796,0.2832,0.0000,0.0133,0.0044,0.5442,0.0000,0.4027,0.5973
7146,Annapolis,64.0,0.6719,0.2500,0.0313,0.0000,0.0000,0.0000,0.0156,0.0156,0.0156,0.0781,0.9219

In [9]:
def ethnicity(m):
    assert isinstance(m,basestring), 'string type only'
    df2016 = pd.read_csv(m)
    df2016= df2016[df_names]
    y=[]
    df_temp= df.loc[df['VARIABLE NAME'].str.contains('UG')]
    y=np.append(y,df_temp.index.get_values())
    df_temp= df.loc[df['VARIABLE NAME'].str.contains('CITY')]
    y=np.append(y,df_temp.index.get_values())
    y.sort()
    df_temp= df.ix[y]
    ethnic = df_temp['VARIABLE NAME'].tolist()
    df_ethnic = df2016[ethnic]
    len(y)
    m=[]
    for i in range(len(y)):
        q = df_ethnic.loc[1].isnull()
        if q[i] == False:
            m=np.append(m,ethnic[i])
    df_ethnic= df_ethnic[m]  
    df_ethnic.dropna()
    
    return df_ethnic

In [10]:
ethnicity('MERGED2015_16_PP.csv')

,CITY,UGDS,UGDS_WHITE,UGDS_BLACK,UGDS_HISP,UGDS_ASIAN,UGDS_AIAN,UGDS_NHPI,UGDS_2MOR,UGDS_NRA,UGDS_UNKN,UGDS_MEN,UGDS_WOMEN
0,Normal,4505.0,0.0340,0.9216,0.0058,0.0018,0.0022,0.0018,0.0000,0.0062,0.0266,0.4617,0.5383
1,Birmingham,11269.0,0.5863,0.2541,0.0317,0.0595,0.0023,0.0006,0.0389,0.0181,0.0085,0.4116,0.5884
2,Montgomery,308.0,0.2110,0.3409,0.0195,0.0000,0.0000,0.0032,0.0000,0.0000,0.4253,0.4286,0.5714
3,Huntsville,5829.0,0.7024,0.1230,0.0417,0.0381,0.0130,0.0000,0.0201,0.0317,0.0300,0.5740,0.4260
4,Montgomery,4740.0,0.0165,0.9251,0.0116,0.0032,0.0008,0.0006,0.0114,0.0209,0.0099,0.3850,0.6150
5,Tuscaloosa,31005.0,0.7807,0.1092,0.0399,0.0113,0.0035,0.0009,0.0271,0.0245,0.0029,0.4525,0.5475
6,Alexander City,1546.0,0.7141,0.2600,0.0123,0.0045,0.0019,0.0000,0.0032,0.0019,0.0019,0.4017,0.5983
7,Athens,2904.0,0.7817,0.1185,0.0189,0.0062,0.0152,0.0007,0.0189,0.0055,0.0344,0.3485,0.6515
8,Montgomery,4142.0,0.5355,0.3510,0.0070,0.0241,0.0051,0.0017,0.0316,0.0316,0.0123,0.3595,0.6405
9,Auburn,21551.0,0.8420,0.0671,0.0323,0.0250,0.0063,0.0001,0.0057,0.0131,0.0085,0.5095,0.4905
10,Birmingham,1346.0,0.7912,0.1137,0.0208,0.0535,0.0097,0.0000,0.0089,0.0000,0.0022,0.5022,0.4978
11,Phenix City,1566.0,0.4662,0.4393,0.0453,0.0109,0.0038,0.0057,0.0166,0.0000,0.0121,0.3870,0.6130
12,Selma,379.0,0.0317,0.9077,0.0317,0.0026,0.0000,0.0000,0.0000,0.0264,0.0000,0.5541,0.4459
13,Montgomery,460.0,0.3283,0.5913,0.0217,0.0152,0.0109,0.0087,0.0000,0.0022,0.0217,0.2500,0.7500
14,Enterprise,1528.0,0.6296,0.2435,0.0582,0.0216,0.0046,0.0033,0.0334,0.0007,0.0052,0.5177,0.4823
15,Bay Minette,4372.0,0.6921,0.2246,0.0341,0.0089,0.0185,0.0018,0.0165,0.0016,0.0018,0.3840,0.6160
16,Montgomery,2282.0,0.3996,0.5079,0.0241,0.0026,0.0061,0.0026,0.0193,0.0215,0.0162,0.3874,0.6126
17,Gadsden,4613.0,0.6978,0.1968,0.0308,0.0046,0.0113,0.0011,0.0269,0.0212,0.0095,0.3909,0.6091
18,Albertville,91.0,0.8791,0.0220,0.0989,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
19,Dothan,4173.0,0.6348,0.3094,0.0268,0.0065,0.0055,0.0017,0.0134,0.0000,0.0019,0.3412,0.6588
20,Hanceville,4821.0,0.8486,0.0631,0.0380,0.0073,0.0097,0.0000,0.0000,0.0075,0.0259,0.3700,0.6300
21,Selma,1383.0,0.1902,0.7628,0.0072,0.0029,0.0022,0.0000,0.0043,0.0051,0.0253,0.3427,0.6573
22,Birmingham,360.0,0.3722,0.5083,0.0333,0.0000,0.0028,0.0056,0.0444,0.0000,0.0333,0.4889,0.5111
23,Montgomery,1160.0,0.6310,0.2164,0.0345,0.0060,0.0095,0.0009,0.0310,0.0017,0.0690,0.4991,0.5009
24,Florence,58.0,0.7586,0.1552,0.0172,0.0000,0.0345,0.0000,0.0172,0.0172,0.0000,0.9483,0.0517
25,Huntsville,820.0,0.3671,0.5561,0.0195,0.0073,0.0134,0.0000,0.0207,0.0098,0.0061,0.4524,0.5476
26,Jacksonville,6625.0,0.6981,0.2214,0.0124,0.0059,0.0075,0.0006,0.0000,0.0260,0.0281,0.4312,0.5688
27,Brewton,1036.0,0.5647,0.3098,0.0068,0.0203,0.0193,0.0000,0.0145,0.0000,0.0647,0.4392,0.5608
28,Birmingham,7381.0,0.6708,0.2187,0.0377,0.0191,0.0031,0.0011,0.0285,0.0207,0.0004,0.3842,0.6158
29,Tanner,8547.0,0.6595,0.1864,0.0461,0.0296,0.0161,0.0004,0.0424,0.0075,0.0121,0.4483,0.5517
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7563,Morrow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7564,Roswell,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7565,Douglasville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7566,Lithonia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7567,Savannah,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7568,Augusta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7569,Columbus,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7570,Columbia,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7571,North Charleston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7572,Irving,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7573,Houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7574,Houston,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7575,Plano,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7576,Cedar Hill,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7577,Dallas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7578,San Antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7579,Stafford,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7580,Fremont,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7581,Newark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7582,New Orleans,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7583,Merced,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7584,El Paso,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7585,Austin,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7586,Emeryville,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7587,Overland Park,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7588,Highland Heights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7589,San Jose,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7590,Lancaster,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7591,San Antonio,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7592,Newark,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN